package cn.tpl.opc.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Author: Luo GuoWen
 * Email: luoguowen123@qq.com
 * Time: 2024/04/15
 * 缓冲垫明详情表
 */
@Data
public class CushionDetailEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cushion_detail
     *
     * @mbg.generated Mon Apr 15 16:08:36 CST 2024
     */
    private static final long serialVersionUID = 1L;
    /**
     * 主键ID
     */
    private Long id;
    /**
     * 缓冲垫二维码
     */
    private String qrCode;
    /**
     * 产线，例如：1，2，3...
     */
    private Integer workLine;
    /**
     * 创建时间
     */
    private Date createdDate;
    /**
     * 更新时间
     */
    private Date modifiedDate;
    /**
     * 扫码器安装顺序
     */
    private Integer scannerSeq;
    /**
     * 开口数
     */
    private Integer openCount;
}
