package cn.tpl.opc.entity;

import java.io.Serializable;
import java.util.Date;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

/**
 * Author: Luo GuoWen
 * Email: luoguowen123@qq.com
 * Time: 2023/04/17
 * 缓冲垫信息表
 */
@Data
public class CushionInfoEntity implements Serializable {
    /**
     * 主键ID
     */
    private Long id;

    /**
     * 缓冲垫二维码
     */
    private String qrCode;

    /**
     * 最大使用次数
     */
    private Integer maxUseCount;

    /**
     * 已使用次数
     */
    private Integer usedCount;

    /**
     * 产线
     */
    private Integer workLine;

    /**
     * 最近一次扫码时间
     */
    private Date lastScanDate;

    /**
     * 创建时间
     */
    private Date createdDate;

    /**
     * 更新时间
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cushion_info
     *
     * @mbg.generated Mon Apr 17 09:21:42 CST 2023
     */
    private static final long serialVersionUID = 1L;
}