package cn.tpl.opc.entity;

import java.io.Serial;
import java.io.Serializable;
import java.util.Date;

import com.alibaba.excel.annotation.ExcelIgnore;
import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.annotation.format.DateTimeFormat;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

/**
 * Author: Luo GuoWen
 * Email: luoguowen123@qq.com
 * Time: 2024/04/15
 * 缓冲垫明详情表
 */
@TableName("cushion_detail")
@Data
public class CushionDetailEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cushion_detail
     *
     * @mbg.generated Mon Apr 15 16:08:36 CST 2024
     */
    @Serial
    private static final long serialVersionUID = 1L;
    /**
     * 主键ID
     */
    @ExcelProperty("ID")
    private Long id;
    /**
     * 缓冲垫二维码
     */
    @ExcelProperty("二维码")
    private String qrCode;
    /**
     * 产线，例如：1，2，3...
     */
    @ExcelProperty("产线")
    private Integer workLine;
    /**
     * 扫码器安装顺序
     */
    @ExcelProperty("安装顺序")
    private Integer scannerSeq;
    /**
     * 扫码器设备ID
     */
    @ExcelIgnore
    private Long scannerId;
    /**
     * 扫码器安装位置
     */
    @ExcelProperty("位置")
    private String scannerPosition;
    /**
     * 开口数
     */
    @ExcelProperty("开口数")
    private Short openCount;
    /**
     * 创建时间
     */
    @ExcelProperty("扫码时间")
    @DateTimeFormat("yyyy-MM-dd HH:mm:ss")
    private Date createdDate;
    /**
     * 更新时间
     */
    @ExcelIgnore
    private Date modifiedDate;
}
