package cn.tpl.opc.entity;

import java.io.Serial;
import java.io.Serializable;
import java.util.Date;

import lombok.Data;

/**
 * Author: Luo GuoWen
 * Email: luoguowen123@qq.com
 * Time: 2023/04/10
 * 设备信息
 */
@Data
public class DeviceInfoEntity implements Serializable {
    /**
     * 主键ID
     */
    private Long id;

    /**
     * 设备类型，0: 扫码器；1: 三菱PLC；2：汇川PLC
     */
    private Integer type;

    /**
     * 设备IP
     */
    private String ip;

    /**
     * 设备端口号
     */
    private Integer port;

    /**
     * 设备状态，0：未连接；1：活跃中
     */
    private Integer status;

    /**
     * 设备名字
     */
    private String name;

    /**
     * 设备位置
     */
    private String position;

    /**
     * 产线
     */
    private Integer workLine;

    /**
     * 安装顺序，从1开始，不同类型的设备分别计算
     */
    private Integer installSeq;

    /**
     * 创建时间
     */
    private Date createdDate;

    /**
     * 更新时间
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_info
     *
     * @mbg.generated Mon Apr 10 15:23:51 CST 2023
     */
    @Serial
    private static final long serialVersionUID = 1L;
}
