package cn.tpl.opc.entity;

import java.io.Serial;
import java.io.Serializable;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

/**
 * Author: Luo GuoWen
 * Email: luoguowen123@qq.com
 * Time: 2024/01/06
 *
 */
@TableName("opc_config")
@Data
public class OpcConfigEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table opc_config
     *
     * @mbg.generated Sat Jan 06 12:13:27 CST 2024
     */
    @Serial
    private static final long serialVersionUID = 1L;
    private Long id;
    private Integer cushionMaxUseCount;
}
