package cn.tpl.opc.entity;

import java.io.Serial;
import java.io.Serializable;

import lombok.Data;

/**
 * Author: Luo GuoWen
 * Email: luoguowen123@qq.com
 * Time: 2023/08/15
 * PLC寄存器地址
 */
@Data
public class PLCAddrEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plc_addr
     *
     * @mbg.generated Tue Aug 15 10:48:40 CST 2023
     */
    @Serial
    private static final long serialVersionUID = 1L;
    /**
     * 主键ID
     */
    private Long id;
    /**
     * PLC的ID
     */
    private Long plcId;
    /**
     * PLC寄存器地址
     */
    private String addr;
    /**
     * 地址类型
     * 0：扫码失败
     * 1：超出最大使用次数
     * 2：扫码成功
     */
    private Integer type;
    /**
     * 扫码器安装顺序，从1开始
     */
    private Integer scannerSeq;
}