package cn.tpl.opc.entity;

import java.io.Serial;
import java.io.Serializable;
import java.sql.Timestamp;

import lombok.Data;

/**
 * Author: Luo GuoWen
 * Email: luoguowen123@qq.com
 * Time: 2024/11/08
 *
 */
@Data
public class ScanLogEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table scan_log
     *
     * @mbg.generated Fri Nov 08 14:27:17 CST 2024
     */
    @Serial
    private static final long serialVersionUID = 1L;
    /**
     * 主键ID
     */
    private Long id;
    /**
     * 缓冲垫二维码
     */
    private String qrCode;
    /**
     * 日志内容
     */
    private String msg;
    /**
     * 创建时间
     */
    private Timestamp createdDate;
    /**
     * 日志类型，0：普通；1：异常
     */
    private Short msgType;
}
