package cn.tpl.opc.mapper;

import cn.tpl.opc.entity.CushionInfoEntity;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface CushionInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cushion_info
     *
     * @mbg.generated Mon Apr 17 09:21:42 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cushion_info
     *
     * @mbg.generated Mon Apr 17 09:21:42 CST 2023
     */
    int insert(CushionInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cushion_info
     *
     * @mbg.generated Mon Apr 17 09:21:42 CST 2023
     */
    int insertSelective(CushionInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cushion_info
     *
     * @mbg.generated Mon Apr 17 09:21:42 CST 2023
     */
    CushionInfoEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cushion_info
     *
     * @mbg.generated Mon Apr 17 09:21:42 CST 2023
     */
    int updateByPrimaryKeySelective(CushionInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cushion_info
     *
     * @mbg.generated Mon Apr 17 09:21:42 CST 2023
     */
    int updateByPrimaryKey(CushionInfoEntity record);

    CushionInfoEntity findByQrCode(String qrCode);

    List<CushionInfoEntity> listByQrCode(String qrCode);

    int modifyUsedCountByQrCode(CushionInfoEntity cushionInfo);

    int modifyOpenCountByQrCode(CushionInfoEntity cushionInfo);

    IPage<CushionInfoEntity> listByPage(Page<CushionInfoEntity> page);
}