package cn.tpl.opc.mapper;

import cn.tpl.opc.commons.scheme.request.QueryCushionDetailPageScheme;
import cn.tpl.opc.commons.scheme.request.QueryCushionInfoPageScheme;
import cn.tpl.opc.entity.CushionDetailEntity;
import cn.tpl.opc.entity.CushionInfoEntity;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CushionDetailEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cushion_detail
     *
     * @mbg.generated Mon Apr 15 16:08:36 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cushion_detail
     *
     * @mbg.generated Mon Apr 15 16:08:36 CST 2024
     */
    int insert(CushionDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cushion_detail
     *
     * @mbg.generated Mon Apr 15 16:08:36 CST 2024
     */
    int insertSelective(CushionDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cushion_detail
     *
     * @mbg.generated Mon Apr 15 16:08:36 CST 2024
     */
    CushionDetailEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cushion_detail
     *
     * @mbg.generated Mon Apr 15 16:08:36 CST 2024
     */
    int updateByPrimaryKeySelective(CushionDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cushion_detail
     *
     * @mbg.generated Mon Apr 15 16:08:36 CST 2024
     */
    int updateByPrimaryKey(CushionDetailEntity record);

    int modifyOpenCountByQrCode(CushionDetailEntity cushionDetail);

    List<CushionDetailEntity> listByQrCode(String qrCode);

    IPage<CushionDetailEntity> listByPage(Page<CushionDetailEntity> page, @Param("data") QueryCushionDetailPageScheme scheme);

}
