package cn.tpl.opc.mapper;

import cn.tpl.opc.commons.dto.result.DeviceInfoDTO;
import cn.tpl.opc.entity.DeviceInfoEntity;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DeviceInfoEntityMapper extends BaseMapper<DeviceInfoEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Apr 10 15:23:51 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Apr 10 15:23:51 CST 2023
     */
    int insert(DeviceInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Apr 10 15:23:51 CST 2023
     */
    int insertSelective(DeviceInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Apr 10 15:23:51 CST 2023
     */
    DeviceInfoEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Apr 10 15:23:51 CST 2023
     */
    int updateByPrimaryKeySelective(DeviceInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Apr 10 15:23:51 CST 2023
     */
    int updateByPrimaryKey(DeviceInfoEntity record);

    List<DeviceInfoEntity> listDeviceInfoByType(Integer type);

    IPage<DeviceInfoEntity> listByPage(Page<DeviceInfoEntity> page);

    List<DeviceInfoEntity> list();

    List<DeviceInfoEntity> listByWorkLine(Integer workLine);
}