package cn.tpl.opc.mapper;

import cn.tpl.opc.entity.OpcConfigEntity;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface OpcConfigEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opc_config
     *
     * @mbg.generated Sat Jan 06 12:13:27 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opc_config
     *
     * @mbg.generated Sat Jan 06 12:13:27 CST 2024
     */
    int insert(OpcConfigEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opc_config
     *
     * @mbg.generated Sat Jan 06 12:13:27 CST 2024
     */
    int insertSelective(OpcConfigEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opc_config
     *
     * @mbg.generated Sat Jan 06 12:13:27 CST 2024
     */
    OpcConfigEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opc_config
     *
     * @mbg.generated Sat Jan 06 12:13:27 CST 2024
     */
    int updateByPrimaryKeySelective(OpcConfigEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opc_config
     *
     * @mbg.generated Sat Jan 06 12:13:27 CST 2024
     */
    int updateByPrimaryKey(OpcConfigEntity record);
}