package cn.tpl.opc.mapper;

import cn.tpl.opc.entity.PLCAddrEntity;
import cn.tpl.opc.commons.scheme.request.QueryPLCAddrPageScheme;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface PLCAddrEntityMapper extends BaseMapper<PLCAddrEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plc_addr
     *
     * @mbg.generated Tue Aug 15 10:48:40 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plc_addr
     *
     * @mbg.generated Tue Aug 15 10:48:40 CST 2023
     */
    int insert(PLCAddrEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plc_addr
     *
     * @mbg.generated Tue Aug 15 10:48:40 CST 2023
     */
    int insertSelective(PLCAddrEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plc_addr
     *
     * @mbg.generated Tue Aug 15 10:48:40 CST 2023
     */
    PLCAddrEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plc_addr
     *
     * @mbg.generated Tue Aug 15 10:48:40 CST 2023
     */
    int updateByPrimaryKeySelective(PLCAddrEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plc_addr
     *
     * @mbg.generated Tue Aug 15 10:48:40 CST 2023
     */
    int updateByPrimaryKey(PLCAddrEntity record);

    PLCAddrEntity findByTypeAndScannerId(PLCAddrEntity record);

    PLCAddrEntity findDuplicate(PLCAddrEntity record);

    PLCAddrEntity findDifferentPlcByScannerId(PLCAddrEntity record);

    int countByPlcId(Long plcId);

    int countByScannerId(Long scannerId);

    IPage<PLCAddrEntity> listByPage(@Param("page") Page<PLCAddrEntity> page,
                                     @Param("data") QueryPLCAddrPageScheme scheme);

    List<PLCAddrEntity> listByPlcIdAndType(PLCAddrEntity record);

    List<PLCAddrEntity> listByPlcId(Long plcId);
}
