package cn.tpl.opc.mapper;

import cn.tpl.opc.entity.PLCAddrEntity;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PLCAddrEntityMapper extends BaseMapper<PLCAddrEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plc_addr
     *
     * @mbg.generated Tue Aug 15 10:48:40 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plc_addr
     *
     * @mbg.generated Tue Aug 15 10:48:40 CST 2023
     */
    int insert(PLCAddrEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plc_addr
     *
     * @mbg.generated Tue Aug 15 10:48:40 CST 2023
     */
    int insertSelective(PLCAddrEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plc_addr
     *
     * @mbg.generated Tue Aug 15 10:48:40 CST 2023
     */
    PLCAddrEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plc_addr
     *
     * @mbg.generated Tue Aug 15 10:48:40 CST 2023
     */
    int updateByPrimaryKeySelective(PLCAddrEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plc_addr
     *
     * @mbg.generated Tue Aug 15 10:48:40 CST 2023
     */
    int updateByPrimaryKey(PLCAddrEntity record);

    PLCAddrEntity findByTypeAndScannerSeq(PLCAddrEntity record);
}