package cn.tpl.opc.mapper;

import cn.tpl.opc.commons.scheme.request.QueryScanLogScheme;
import cn.tpl.opc.entity.ScanLogEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ScanLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_log
     *
     * @mbg.generated Fri Nov 08 14:27:17 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_log
     *
     * @mbg.generated Fri Nov 08 14:27:17 CST 2024
     */
    int insert(ScanLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_log
     *
     * @mbg.generated Fri Nov 08 14:27:17 CST 2024
     */
    int insertSelective(ScanLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_log
     *
     * @mbg.generated Fri Nov 08 14:27:17 CST 2024
     */
    ScanLogEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_log
     *
     * @mbg.generated Fri Nov 08 14:27:17 CST 2024
     */
    int updateByPrimaryKeySelective(ScanLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scan_log
     *
     * @mbg.generated Fri Nov 08 14:27:17 CST 2024
     */
    int updateByPrimaryKey(ScanLogEntity record);

    List<ScanLogEntity> listAllByScheme(@Param("data") QueryScanLogScheme scheme);
}
