spring:
  profiles:
    active: @env@

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#监控所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: D:\Java\@name@_logs\@name@_@env@.log
