logging:
  file:
    name: ${LOG_FILE:logs/wms-opc-test.log}

spring:
  datasource:
    druid:
      url: ${BUFFERPAD_DB_URL:jdbc:mysql://127.0.0.1:3306/wms_opc?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai}
      username: ${BUFFERPAD_DB_USERNAME:bufferpad}
      password: ${BUFFERPAD_DB_PASSWORD:}
