logging:
  file:
    name: /home/gitlab-runner/application/wms-opc/opc_test.log

spring:
  datasource:
    druid:
      url: jdbc:mysql://192.0.2.6:3306/wms_opc?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: visitor
      password: CHANGE_ME_DB_PASSWORD
