stages:
  - build
  - deploy
variables:
  APP: "opc-0.0.1.-SNAPSHOT"
  APP_PATH: "target/$APP.jar"
  DEPLOY_PATH: "/home/gitlab-runner/application/wms-opc/"
  DEPLOY_APP_PATH: "$DEPLOY_PATH$APP.jar"
  BASH: "reboot_app.sh "
  ENV: "test"
#build过程
build:
  stage: build
  tags:
    - $ENV
  script:
    - echo "======== Build ========="
    - mvn clean deploy -U -P $ENV -DskipTests=true
    - cp $APP_PATH $DEPLOY_APP_PATH
  #分支
  only:
    - master
#发布过程
deploy:
  stage: deploy
  tags:
    - $ENV
  script:
    - echo "======== Deploy ========="
    - bash $BASH$APP
  dependencies:
    - build