-- Correlate all scan/count/PLC events generated by one business operation.
-- Kept in the installer so upgrades from older bundles receive the schema
-- expected by the current backend without re-importing the destructive dump.
SET @column_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'operation_event'
      AND column_name = 'operation_id'
);
SET @column_sql = IF(
    @column_exists = 0,
    'ALTER TABLE operation_event ADD COLUMN operation_id VARCHAR(64) NULL AFTER event_id',
    'SELECT 1'
);
PREPARE operation_event_column_statement FROM @column_sql;
EXECUTE operation_event_column_statement;
DEALLOCATE PREPARE operation_event_column_statement;

UPDATE operation_event
SET operation_id = event_id
WHERE operation_id IS NULL OR operation_id = '';

SET @index_exists = (
    SELECT COUNT(1)
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'operation_event'
      AND index_name = 'idx_operation_event_operation_id'
);
SET @index_sql = IF(
    @index_exists = 0,
    'ALTER TABLE operation_event ADD INDEX idx_operation_event_operation_id (operation_id, id)',
    'SELECT 1'
);
PREPARE operation_event_operation_index_statement FROM @index_sql;
EXECUTE operation_event_operation_index_statement;
DEALLOCATE PREPARE operation_event_operation_index_statement;
